#!/bin/sh
while :; do
    az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	az acr run -r demoas --cmd 'demoas.azurecr.io/demoas:latest' --timeout 28800 /dev/null --no-logs --no-wait
	
done
